// Date: 2013/09/14 01:47:56 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package f01405.TestMod.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class fireBug extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
  
  public fireBug()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape1.setRotationPoint(6F, 19F, 6F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape2.setRotationPoint(6F, 19F, 2F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape3.setRotationPoint(6F, 19F, -4F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape4.setRotationPoint(-8F, 19F, -8F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape5.setRotationPoint(-8F, 19F, 2F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape6.setRotationPoint(-8F, 19F, -4F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape7.setRotationPoint(-8F, 19F, 6F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 0);
      Shape8.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape8.setRotationPoint(-7F, 16.2F, 6F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0.3490659F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape9.setRotationPoint(-7F, 16.2F, 2F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0.3490659F);
      Shape10 = new ModelRenderer(this, 0, 0);
      Shape10.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape10.setRotationPoint(-7F, 16.2F, -8F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0.3490659F);
      Shape11 = new ModelRenderer(this, 0, 0);
      Shape11.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape11.setRotationPoint(-7F, 16.2F, -4F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0.3490659F);
      Shape12 = new ModelRenderer(this, 0, 0);
      Shape12.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape12.setRotationPoint(-7F, 16.2F, -4F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0.3490659F);
      Shape13 = new ModelRenderer(this, 0, 0);
      Shape13.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape13.setRotationPoint(5.1F, 16.9F, -8F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, -0.3490659F);
      Shape14 = new ModelRenderer(this, 0, 0);
      Shape14.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape14.setRotationPoint(6F, 19F, -8F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 0);
      Shape15.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape15.setRotationPoint(5.1F, 16.9F, 6F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, -0.3490659F);
      Shape16 = new ModelRenderer(this, 0, 0);
      Shape16.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape16.setRotationPoint(5.1F, 16.9F, -4F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, -0.3490659F);
      Shape17 = new ModelRenderer(this, 0, 0);
      Shape17.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape17.setRotationPoint(5.1F, 16.9F, 2F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, -0.3490659F);
      Shape18 = new ModelRenderer(this, 0, 0);
      Shape18.addBox(0F, 0F, 0F, 14, 4, 18);
      Shape18.setRotationPoint(-7F, 15F, -9F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 0);
      Shape19.addBox(0F, 0F, 0F, 7, 4, 7);
      Shape19.setRotationPoint(-4F, 11F, -13F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity per6Entity)
  {
	  this.Shape1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape1.rotateAngleY = 0.0F;
	  
	  this.Shape2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape2.rotateAngleY = 0.0F;
	  
	  this.Shape3.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape3.rotateAngleY = 0.0F;
	  
	  this.Shape4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape4.rotateAngleY = 0.0F;
	  
	  this.Shape5.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape5.rotateAngleY = 0.0F;
	  
	  this.Shape6.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape6.rotateAngleY = 0.0F;
	  
	  this.Shape7.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape7.rotateAngleY = 0.0F;
	  
	  this.Shape8.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape8.rotateAngleY = 0.0F;
	  
	  this.Shape9.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape9.rotateAngleY = 0.0F;
	  
	  this.Shape10.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape10.rotateAngleY = 0.0F;
	  
	  this.Shape11.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape11.rotateAngleY = 0.0F;
	  
	  this.Shape12.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	  this.Shape12.rotateAngleY = 0.0F;
	  
	  this.Shape13.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape13.rotateAngleY = 0.0F;
	  
	  this.Shape14.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape14.rotateAngleY = 0.0F;
	  
	  this.Shape15.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape15.rotateAngleY = 0.0F;
	  
	  this.Shape16.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape16.rotateAngleY = 0.0F;
	  
	  this.Shape17.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F *f1;
	  this.Shape17.rotateAngleY = 0.0F;

	  
	  this.Shape19.rotateAngleY = f3 / (180F / (float)Math.PI);
	  this.Shape19.rotateAngleX = f4 / (170F / (float)Math.PI);
  }

}
